repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - harlequin
          - types-pygments
          - importlib_metadata
          - pytest
        args:
          - "--disallow-untyped-calls"
          - "--disallow-untyped-defs"
          - "--disallow-incomplete-defs"
          - "--strict-optional"
          - "--warn-return-any"
          - "--warn-no-return"
          - "--warn-redundant-casts"
          - "--no-warn-unused-ignores"
          - "--allow-untyped-decorators"
