version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume-test:/var/lib/postgresql/data
    restart: unless-stopped

  flight-sql:
    image: voltrondata/flight-sql:latest
    container_name: flight-sql
    tty: true
    init: true
    environment:
      TLS_ENABLED: 1
      FLIGHT_PASSWORD: "flight_password"
      PRINT_QUERIES: 1
    ports:
      - 31337:31337
    restart: unless-stopped


volumes:
  postgres-db-volume-test:
